export const MAIN_ROUTE: string = '/'
export const FAVOURITES_ROUTE: string = '/favourtires'
export const CART_ROUTE: string = '/cart'
export const ABOUT_ROUTE: string = '/about'
export const CATALOG_ROUTE: string = '/catalog'
export const AREAS_ROUTE: string = '/areas'
export const SELL_ROUTE: string = '/sell'
export const PARTNERS_ROUTE: string = '/partners'
export const DELIVERY_ROUTE: string = '/delivery'
export const CONTACTS_ROUTE: string = '/contacts'
export const NOTFOUND_ROUTE: string = '*'

export const FACEBOOK_ROUTE: string = 'https://www.facebook.com/'
export const TELEGRAM_ROUTE: string ='https://web.telegram.org/z/'
export const YOUTUBE_ROUTE: string ='https://www.youtube.com/'
export const INSTAGRAM_ROUTE: string = 'https://www.instagram.com/'

